ShushrutEyeHospitalCRM/Controllers/SetUpController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShushrutEyeHospitalCRM.Helper;
using ShushrutEyeHospitalCRM.Models;
using ShushrutEyeHospitalCRM.Models.DTO;
using ShushrutEyeHospitalCRM.Repositories.Interface;
using ShushrutEyeHospitalCRM.Resources;
using ShushrutEyeHospitalCRM.Services.Implementation;
using ShushrutEyeHospitalCRM.Services.Interface;
using System.Data;

namespace ShushrutEyeHospitalCRM.Controllers
{
    public class SetUpController : Controller
    {
        private readonly IRepositories<CommonEyeProblem> _problems;
        private readonly IRepositories<Medicines> _medicine;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public SetUpController(IRepositories<CommonEyeProblem> problems, UserManager<ApplicationUser> userManager, IMapper mapper, IRepositories<Medicines> medicine)
        {
            _problems = problems;
            _userManager = userManager;
            _mapper = mapper;
            _medicine = medicine;
        }
        [Authorize(Roles = CommonHelper.Admin)]
        
        public async Task<IActionResult> AddEditEyeProblems(int Id = 0)
        {
            var request = new CommonEyeProblemViewModel();
            if (Id > 0)
            {
                var response = await _problems.GetByIdAsync(Id);
                request = (_mapper.Map<CommonEyeProblemViewModel>(response));
            }
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> AddEditEyeProblems([FromForm] CommonEyeProblemViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.ProblemId == 0)
                {
                    var modeldata = _mapper.Map<CommonEyeProblem>(model);
                    modeldata.IsActive = true;
                    var save = await _problems.CreateAsync(modeldata);
                }
                else
                {
                    var res = await _problems.GetByIdAsync(model.ProblemId);
                    if (res != null)
                    {
                        res.ProblemName = model.ProblemName;
                        var save =await _problems.UpdateAsync(res);
                    }
                }
                return Json(new { message = "Successfully Done", status = true });
            }
            else
            {
                return Json(new { message = "Failed to save", status = false });
            }
        }

        [Authorize(Roles = CommonHelper.Admin)]
        public async Task<IActionResult> ProblemList()
        {
            var problemList = await _problems.GetAllAsync();
            var data = _mapper.Map<IEnumerable<CommonEyeProblemViewModel>>(problemList);
            return View(data);
        }
        [Authorize(Roles = CommonHelper.Admin)]
        [HttpDelete]
        public async Task<IActionResult> DeleteProblem(int Id)
        {
            var check = await _problems.GetByIdAsync(Id);
            if (check != null)
            {
                await _problems.DeleteAsync(check);
                return Json(new { message = CommonResource.DeleteSuccess, status = true });

            }
            else
            {
                return Json(new { message = "Invalid Problem", status = false });
            }
        }

        [Authorize(Roles = CommonHelper.Admin)]

        public async Task<IActionResult> AddEditMedicine(int Id = 0)
        {
            var request = new MedicineViewModel();
            if (Id > 0)
            {
                var response = await _medicine.GetByIdAsync(Id);
                request = (_mapper.Map<MedicineViewModel>(response));
            }
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> AddEditMedicine([FromForm] MedicineViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.MedicineId == 0)
                {
                    var modeldata = _mapper.Map<Medicines>(model);
                    modeldata.IsActive = true;
                    var save = await _medicine.CreateAsync(modeldata);
                }
                else
                {
                    var res = await _medicine.GetByIdAsync(model.MedicineId);
                    if (res != null)
                    {
                        res.MedicineName = model.MedicineName;
                        var save = await _medicine.UpdateAsync(res);
                    }
                }
                return Json(new { message = "Successfully Done", status = true });
            }
            else
            {
                return Json(new { message = "Failed to save", status = false });
            }
        }

        [Authorize(Roles = CommonHelper.Admin)]
        public async Task<IActionResult> MedicineList()
        {
            var medicineList = await _medicine.GetAllAsync();
            var data = _mapper.Map<IEnumerable<MedicineViewModel>>(medicineList);
            return View(data);
        }
        [Authorize(Roles = CommonHelper.Admin)]
        [HttpDelete]
        public async Task<IActionResult> DeleteMedicine(int Id)
        {
            var check = await _medicine.GetByIdAsync(Id);
            if (check != null)
            {
                await _medicine.DeleteAsync(check);
                return Json(new { message = CommonResource.DeleteSuccess, status = true });

            }
            else
            {
                return Json(new { message = "Invalid medicine", status = false });
            }
        }

        public async Task<IActionResult> SearchProblem(string prefix)
        {
            var problemList = await _problems.GetAllAsync();
            var res = problemList.Where(w => w.ProblemName.StartsWith(prefix));
            var data = _mapper.Map<IEnumerable<CommonEyeProblemViewModel>>(res);
            return Json(data);
        }
        [HttpGet]
        public async Task<IActionResult> SearchMedicine(string prefix)
        {
            var medilist = await _medicine.GetAllAsync();
            if (!string.IsNullOrEmpty(prefix))
            {
                medilist = medilist.Where(w => w.MedicineName.StartsWith(prefix));
            }
            var data = _mapper.Map<IEnumerable<MedicineViewModel>>(medilist);
            return Json(data);
        }
    }
}

ShushrutEyeHospitalCRM/Views/SetUp/AddEditEyeProblems.cshtml
@model CommonEyeProblemViewModel
<link rel="stylesheet" type="text/css" href="~/css/jquery_validation.css" />
<link href="~/css/jquery-ui.css" rel="stylesheet" />

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon">
            <i class="pe-7s-note2"></i>
        </div>
        <div class="header-title">
            <h1>Master</h1>
            <small>Problem List</small>
            <ol class="breadcrumb hidden-xs">
                <li><a href="~/Home/Index"><i class="pe-7s-home"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- Form controls -->
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="~/SetUp/ProblemList">
                                <i class="fa fa-list"></i>  Problem List
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("AddEditEyeProblems", "SetUp", FormMethod.Post, new { @id = "frmAddEditEyeProblems" }))
                        {
                            <form id="frmAddPatient">
                                <div class="row">
                                    <div class="form-group col-sm-12">
                                        <label>First Name<span class="text-danger">*</span></label>
                                        @Html.TextBoxFor(m=>m.ProblemName,new{@Id="txtProblemName",@class="form-control",placeholder="Enter Problem",required=""})
                                        @Html.HiddenFor(m=>m.ProblemId)
                                        @Html.ValidationMessageFor(m=>m.ProblemName)
                                    </div>

                                    <div class="col-sm-12 reset-button">
                                        <button type="submit" id="btnSave" class="btn btn-success">Save</button>
                                        <button type="reset" id="btnReset" class="btn btn-warning">Reset</button>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- /.content -->
</div>
@section scripts{
    <!-- jquery validation -->
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script type="text/javascript" src="~/js/SetUp.js"></script>
}

ShushrutEyeHospitalCRM/Views/SetUp/AddEditMedicine.cshtml
@model MedicineViewModel
<link rel="stylesheet" type="text/css" href="~/css/jquery_validation.css" />
<link href="~/css/jquery-ui.css" rel="stylesheet" />

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon">
            <i class="pe-7s-note2"></i>
        </div>
        <div class="header-title">
            <h1>Master</h1>
            <small>Medicine List</small>
            <ol class="breadcrumb hidden-xs">
                <li><a href="~/Home/Index"><i class="pe-7s-home"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- Form controls -->
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="~/SetUp/MedicineList">
                                <i class="fa fa-list"></i>  Medicine List
                            </a>
                        </div>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("AddEditMedicine", "SetUp", FormMethod.Post, new { @id = "frmAddEditMedicine" }))
                        {
                            <form id="frmAddPatient">
                                <div class="row">
                                    <div class="form-group col-sm-12">
                                        <label>Medicine Name<span class="text-danger">*</span></label>
                                        @Html.TextBoxFor(m=>m.MedicineName,new{@Id="txtMedicineName",@class="form-control",placeholder="Enter Medicine Name",required=""})
                                        @Html.HiddenFor(m=>m.MedicineId)
                                        @Html.ValidationMessageFor(m=>m.MedicineName)
                                    </div>

                                    <div class="col-sm-12 reset-button">
                                        <button type="submit" id="btnSave" class="btn btn-success">Save</button>
                                        <button type="reset" id="btnReset" class="btn btn-warning">Reset</button>
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- /.content -->
</div>
@section scripts{
    <!-- jquery validation -->
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script type="text/javascript" src="~/js/SetUp.js"></script>
}

ShushrutEyeHospitalCRM/Views/SetUp/MedicineList.cshtml
@using System.Security.Claims;
@model List<MedicineViewModel>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon">
            <i class="pe-7s-box1"></i>
        </div>
        <div class="header-title">
            <h1>Master</h1>
            <small>Medicine List</small>
            <ol class="breadcrumb hidden-xs">
                <li><a href="~/Home/Index"><i class="pe-7s-home"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">


        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group">
                            <a class="btn btn-success" href="~/SetUp/AddEditMedicine"> <i class="fa fa-plus"></i>  Add Medicine</a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead class="success">
                                    <tr>
                                        <th>Sr No</th>
                                        <th>Medicine</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Any())
                                    {
                                        int i = 0;
                                        foreach (var item in Model)
                                        {
                                            i++;
                                            <tr>
                                                <td>
                                                    <label>@i</label>
                                                </td>
                                                <td>@item.MedicineName</td>
                                                <td style="width: 80px;">
                                                    <a href="/SetUp/AddEditMedicine?Id=@item.MedicineId" class="btn btn-info btn-xs" target="_blank">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <button type="button" class="btn btn-danger btn-xs" id="btndelete" onclick="DeleteMedicine(@item.MedicineId)">
                                                        <i class="fa fa-trash-o"></i>
                                                    </button>
                                                </td>

                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- /.content -->
</div>
<script src="~/js/SetUp.js"></script>

ShushrutEyeHospitalCRM/Views/SetUp/ProblemList.cshtml
@using System.Security.Claims;
@model IEnumerable<CommonEyeProblemViewModel>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="header-icon">
            <i class="pe-7s-box1"></i>
        </div>
        <div class="header-title">
            <h1>Master</h1>
            <small>Problem List</small>
            <ol class="breadcrumb hidden-xs">
                <li><a href="~/Home/Index"><i class="pe-7s-home"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">


        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-bd lobidrag">
                    <div class="panel-heading">
                        <div class="btn-group">
                            <a class="btn btn-success" href="~/SetUp/AddEditEyeProblems?Id=0"> <i class="fa fa-plus"></i>  Add Problem</a>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead class="success">
                                    <tr>
                                        <th>Sr No</th>
                                        <th>Problem</th>
                                        <th>Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Any())
                                    {
                                        int i = 0;
                                        foreach (var item in Model)
                                        {
                                            i++;
                                            <tr>
                                                <td>
                                                    <label>@i</label>
                                                </td>
                                                <td>@item.ProblemName</td>
                                                <td style="width: 80px;">
                                                    <a href="/SetUp/AddEditEyeProblems?Id=@item.ProblemId" class="btn btn-info btn-xs" target="_blank">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    <button type="button" class="btn btn-danger btn-xs" id="btndelete" onclick="DeleteProblem(@item.ProblemId)">
                                                        <i class="fa fa-trash-o"></i>
                                                    </button>
                                                </td>

                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> <!-- /.content -->
</div>
<script src="~/js/SetUp.js"></script>